# Generated by Django 4.2.4 on 2023-09-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organisation',
        ),
    ]
